print("\n")
print("###############################")
print("#                             #")
print("#        Solehol Akmal        #")
print("#        2610817210004        #")
print("#                             #")
print("###############################")
print("\n")