print("\nInput Data Mahasiswa")
name = input("Nama : ")
id = int(input("NIM : "))
parallelClass = input("Kelas Paralel : ")
birthPlaceAndDate = input("Tempat/Tanggal Lahir : ")
address = input("Alamat : ")
hobby = input("Hobi : ")
phoneNumber = int(input("Nomor HP : "))

print("\n------------------------------------------------------\n")

print(f"Nama                 : {name}")
print(f"NIM                  : {id}")
print(f"Kelas Paralel        : {parallelClass}")
print(f"Tempat/Tanggal Lahir : {birthPlaceAndDate}")
print(f"Alamat               : {address}")
print(f"Hobi                 : {hobby}")
print(f"Nomor HP             : {phoneNumber}")
print("\n")